[package]
name = "openlink-api"
version.workspace = true
edition.workspace = true

[[bin]]
name = "openlink"
path = "src/main.rs"

[dependencies]
openlink-core = { path = "../openlink-core" }
openlink-store = { path = "../openlink-store" }
ext-redirect = { path = "../../extensions/ext-redirect" }
ext-webhook = { path = "../../extensions/ext-webhook" }
ext-conditions = { path = "../../extensions/ext-conditions" }
ext-hooks = { path = "../../extensions/ext-hooks" }
ext-json = { path = "../../extensions/ext-json" }
serde = { workspace = true }
serde_json = { workspace = true }
async-trait = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
chrono = { workspace = true }
uuid = { workspace = true }
rand = "0.8"
tokio = { workspace = true }
toml = { workspace = true }

# Axum + HTTP
axum = "0.7"
tower-http = { version = "0.5", features = ["cors", "trace"] }
tower = "0.4"
